repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
      stages:
        - commit
    
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      require_serial: true
      stages:
        - commit
      types: [python]

    - id: black
      name: black
      entry: black
      language: system
      require_serial: true
      types: [python]
      stages:
        - commit

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      args: ["--ignore=E203,W503,E712", --max-line-length=120]
      types: [python]
      stages:
        - commit

    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      stages:
        - commit

    - id: pyright
      name: pyright
      entry: pyright
      entry: pyright
      language: system
      types: [python]
      stages:
        - commit
